---
title: "CPBMI R Ch6. Basic Graphics 2"
author: "JW Yi"
date: "Monday, September 29, 2014"
output:
  html_document:
    highlight: pygments
    theme: united
---

# Points Plot, using Iris data
```{r}
head(iris)
summary(iris)
attach(iris)
str(Species)
head(unclass(Species))
class(head(unclass(Species)))

c("red","green","blue")[1]
c("red","green","blue")[2]

plot(Sepal.Width, Sepal.Length, pch=21, bg=c("red","green","blue")[unclass(Species)])
legend("topleft", legend=c("setosa", "versicolor", "virginica"),
        pch=c(21, 21, 21), pt.bg=c("red", "green3", "blue") , col=c("red", "green3", "blue"))
```

# Pairs Plot : pairs()
```{r}
pairs(iris[,1:4])

par(bg="cornsilk")
pairs(iris[,1:4], main = "Iris Data", pch = 21, bg = c("red", "green3", "blue")[unclass(iris$Species)])
```

# Arrows 
## arrows(from, to, code=1~3, angle=0~90)
```{r}
par(bg="white")
par(mfrow=c(2,2))
plot(1:7, 1:7, type="n", xlab="", ylab="") 
arrows(2,2, 2,6, code=1)
arrows(4,2, 4,6, code=2)
arrows(6,2, 6,6, code=3)
title(main="code = 1 ~ 3")

plot(1:7, 1:7, type="n", , xlab="", ylab="") 
arrows(2,2, 2,6, code=1, angle=30) 
arrows(4,2, 4,6, code=1, angle=60) 
arrows(6,2, 6,6, code=1, angle=90)
title(main="code = 1, angle=30,60,90")

plot(1:7, 1:7, type="n", , xlab="", ylab="") 
arrows(2,2, 2,6, code=2, angle=30) 
arrows(4,2, 4,6, code=2, angle=60) 
arrows(6,2, 6,6, code=2, angle=90)
title(main="code = 2, angle=30,60,90")

plot(1:7, 1:7, type="n", , xlab="", ylab="") 
arrows(2,2, 2,6, code=3, angle=30) 
arrows(4,2, 4,6, code=3, angle=60) 
arrows(6,2, 6,6, code=3, angle=90)
title(main="code = 3, angle=30,60,90")
```

# Barplot with Error Bar
```{r}
par(mfrow=c(1,1))
library(dplyr)
library(reshape2)
birthwt <- read.table("D://Work/birthwt2.txt", header=T)
attach(birthwt)

bwt.mean <- mean(bwt)
bwt.sd.upper <- mean(bwt) + sd(bwt)
bwt.sd.lower <- mean(bwt) - sd(bwt)

b <- barplot(bwt.mean, ylim=c(0, max(bwt)))
arrows(b, bwt.sd.upper, b, bwt.sd.lower, angle=90, code=3) 
text(b, bwt.sd.upper + 250, "**")
text(b, bwt.sd.upper + 550, "p value < 0.05", cex=0.8)
box()
```

# Barplot with Error Bar : Group by Race, Smoke
```{r}
bwt.mean <- birthwt %.%
     group_by(race, smoke) %.%
     summarise(bwt.mean = mean(bwt))
bwt.mean
bwt.mean.cast <- dcast(bwt.mean, smoke ~ race, value.var="bwt.mean")
bwt.mean.cast

bwt.sem <- birthwt %.%
     group_by(race, smoke) %.%
     summarise(bwt.sem = sd(bwt)/sqrt(n()))
bwt.sem
bwt.sem.upper <- bwt.mean$bwt.mean + bwt.sem$bwt.sem
bwt.sem.lower <- bwt.mean$bwt.mean - bwt.sem$bwt.sem
bwt.sem.upper
bwt.sem.lower

b <- barplot(as.matrix(bwt.mean.cast[,2:4]), beside=TRUE, legend.text=unique(bwt.mean$smoke), 
             args.legend = list(x="topleft"), ylim=c(0, 4500))
b

arrows(b, bwt.sem.upper, b, bwt.sem.lower, code=3, angle=90, length=0.05)

axis(1, at=c(1.5, 2.5), tick=TRUE, pos=3300, labels=c("",""))
text(2, 3400, "**")

axis(1, at=c(7.5, 8.5), tick=TRUE, pos=3800, labels=c("",""))
text(8, 3900, "***")
box()
```

# Boxplot
```{r}
boxplot(bwt ~ race, ylim=c(0, 6000))

axis(1, at=c(1, 2), tick=TRUE, pos=4500, labels=c("",""))
text(1.5, 4800, "p-value > 0.05")
axis(1, at=c(2, 3), tick=TRUE, pos=5500, labels=c("",""))
text(2.5, 5800, "**")
axis(3, at=c(1, 3), tick=TRUE, pos=300, labels=c("",""))
text(2, 100, "***")
```
