---
output:
  html_document:
    highlight: pygments
    theme: united
---
CPBMI R CH1. Homework
=====================
(1) Newborn, age and weight

a) Create vector
```{r}
age <- c(1,3,5,2,11,9,3,9,12,3)
weight <- c(4.4,5.3,7.2,5.2,8.5,7.3,6.0,10.4,10.2,6.1)
```

b) Mean, Median, Variance, Standard deviation
```{r}
summary(age)
var(age)
sd(age)

summary(weight)
var(weight)
sd(weight)
```

c) Correlation between age and weight
```{r}
cor(age,weight)
```

d) Convert unit into pound
```{r}
weight.pound <- age * 2.2
weight.pound
```

e) Finding specific values, indexing
```{r}
weight[weight>8]
which(weight>8)
```

(2) Matrix practice

a) Create matrix
```{r}
mat <- matrix(c(1:12), nrow=3, byrow=TRUE)
mat
```

b) Naming row and column
```{r}
rownames(mat) <- c("I","II","III")
colnames(mat) <- c("one","two","three","four")
mat
```

c) Substitute specific value
```{r}
mat[2,3] <- 88
mat
```

d) Finding values and indexing
```{r}
mat[mat>10]
which(mat>10, arr.ind=TRUE)
```

e) Calculate within a colunm or row
```{r}
sum(mat[,3])
mean(mat[2,])
```