---
title: "Ch 11 Clustering Analysis"
author: "JW Yi"
date: "Thursday, October 02, 2014"
output:
  html_document:
    highlight: pygments
    theme: united
---

# Hierarchical clustering
## Simple Example
```{r}
par(mfrow=c(2,1))
x1 <- c(1,2,3,4,7,8,10)
x2 <- c(8,2,3,1,11,8,10)
X <- cbind(x1, x2)
plot(X, pch=16)
identify(X, labels=1:7)
X.hclust <- hclust(dist(X), method = "single")
dist(X)
plot(X.hclust)
```

## Europe Data
```{r}
europe <- read.csv("europe.csv")
head(europe)
europe.hclust <- hclust(dist(europe[-1]))  # Distance Calculation without Country 
par(mfrow=c(1,1))
plot(europe.hclust, labels = europe$Country)
rect.hclust(europe.hclust, 5)  # Clustering into 5 groups, and display with red square
cutree(europe.hclust, 5) 
```

# K-means clustering
```{r}
europe.kmeans <- kmeans(europe[-1],5)
names(europe.kmeans)
europe.kmeans
europe.kmeans$cluster
europe.kmeans.cluster <- data.frame(Country=europe$Country, cluster=europe.kmeans$cluster)
head(europe.kmeans.cluster)
europe.kmeans.cluster[europe.kmeans.cluster$cluster==2,]
```

# Multi Dimensional Scaling (MDS)
```{r}
europe.extract <- europe[-c(1:3)]
europe.extract.mds <- cmdscale(dist(europe.extract))
plot(europe.extract.mds, type="n")
text(europe.extract.mds, as.character(europe$Country), cex=1.0)
europe.extract.mds <- cmdscale(dist(europe.extract), k=3)
```

## 3D plot
```{r}
library(rgl)
plot3d(europe.extract.mds, type="n")
text3d(europe.extract.mds, text=as.character(europe$Country))
```

# Heatmap
```{r}
rownames(europe.extract) <- as.character(europe$Country)
heatmap(as.matrix(dist(europe.extract)))
```
