---
title: "Ch 15 Survival Analysis"
author: "JW Yi"
date: "Thursday, October 02, 2014"
output:
  html_document:
    highlight: pygments
    theme: united
---

# Survival Analysis
```{r}
library(survival)
library(ISwR)
head(melanom)
attach(melanom)
```

## Create Surv Object
```{r}
Surv(days, status == 1)  # Surv(time, event)
head(Surv(days, status==1))
```

# (1) Kaplna-Meier estimator
```{r}
surv.bysex <- survfit(Surv(days, status == 1)~sex)
summary(surv.bysex)
plot(surv.bysex)
plot(surv.bysex, conf.int=TRUE, col=c("red", "blue"))
```

# (2) Log - Rank test
```{r}
survdiff(Surv(days, status == 1)~sex)
```

## Stratified analysis = strata(...), cluster(...)
```{r}
survdiff(Surv(days, status==1)~sex + strata(ulc))  
```

# (3) Cox proportional hazard model
```{r}
summary(coxph(Surv(days, status == 1) ~ sex))
summary(coxph(Surv(days, status == 1) ~ sex + log(thick) + strata(ulc)))
```

# Survival ovarian cancer under monotherapy or combined
```{r}
detach(melanom)

mydata <- read.csv("http://cpbmi.or.kr/ovarian.csv")
attach(mydata)
head(mydata)

mysurv <- Surv(time, status == 1)
myKMtest <- survfit(mysurv ~ group, conf.int=FALSE)

plot(myKMtest, lty=c(1,3), col=c("blue", "red"))
title (main = "Survival ovarian cancer n=26", 
       xlab="Time (days)", ylab = "% surviving, S(t)")
legend(x=10, y=0.25, legend = c("monotherapy", "combined"), 
       col=c("blue", "red"), lty=c(1,1))
summary(myKMtest)

my_coxph_full <- coxph(mysurv ~ group + age, mydata)
summary(my_coxph_full)

my_coxph_reduced <- coxph(mysurv ~ age, mydata)
summary(my_coxph_reduced)

## testing deviance
anova(my_coxph_full, my_coxph_reduced, test="Chisq")
```
