---
title: "Ch 12 Contrasts"
author: "JW Yi"
date: "Thursday, October 02, 2014"
output: html_document
---

# Define Contrasts
```{r}
irrigation <- factor(c(rep("Control",10),
  rep("Irrigated 10 mm", 10), 
  rep("Irrigated 20 mm", 10)))
biomass <- 1:30
boxplot(biomass~irrigation)
summary(aov(biomass~irrigation))

contrast1 <- c(-2,1,1)
contrast2 <- c(0,1,-1)
contrasts(irrigation) <- cbind(contrast1, contrast2)
contrasts(irrigation)

summary.lm(aov(biomass~irrigation))
```

# Placebo vs Low/High Dose
```{r}
effect <- c(3,2,1,1,4,5,2,4,3,4,7,4,5,3,6)
dose <- gl(3,5,labels=c("Placebo", "Low Dose", "High Dose"))
effectData <- data.frame(dose, effect)
contrast1 <- c(-2,1,1)
contrast2 <- c(0,-1,1)
contrasts (effectData$dose) <- cbind(contrast1, contrast2)
effectData$dose
effectPlanned <- aov(effect~dose, data=effectData)
summary.lm(effectPlanned)
```

# Automatic Contrast Creation
```{r}
contr.treatment(factor(c("Low Dose", "High Dose", "Placebo")))
contr.treatment(factor(c("Low Dose", "High Dose", "Placebo")), base=3)
contr.SAS(factor(c("Placebo", "Low Dose", "High Dose")))
contr.helmert(factor(c("Placebo", "Low Dose", "High Dose")))
contr.helmert(factor(c("E1", "E2", "E3", "C1", "C2")))
```

