---
title: "Ch 10 Multiple Regression"
author: "JW Yi"
date: "Thursday, October 02, 2014"
output:
  html_document:
    highlight: pygments
    theme: united
---
# Multiple Regression Formula
## Example 1
```{r}
X1 <- c(4,4,6,6,8,8)
X2 <- c(2,6,2,6,2,6)
Y <- c(64,81,72,91,83,96)
dat <- data.frame(Y, X1, X2)
summary(lm(Y~X1+X2, data=dat))
```
Y = 39.333 + 4.250 X1 + 4.083 X2 + error

## Example 2
```{r}
X1 <- c(195, 179, 205, 204, 201, 184, 210, 209)
X2 <- c(57, 61, 60, 62, 61, 54, 58, 61)
Y <- c(81.4, 122.2, 101.7, 175.6, 150.3, 64.8, 92.1, 113.8)
dat <- data.frame (Y, X1, X2)
summary (dat)
dim(dat)
summary (lm(Y ~ X1 + X2, data = dat))
summary (lm(Y ~ X2, data = dat))
```

# Calculating Tolerance (T), Variance Inflation Factor (VIF)
```{r}
dat <- read.table("fat.txt", header=T, sep='\t')
pairs(dat[2:4])
cor(dat[2:4])

R1 <- summary(lm(triceps ~ tight + wrist, data=dat))$r.squared
T1 = 1 - R1
T1
VIF = 1 / T1
VIF

R2 <- summary(lm(tight ~ triceps + wrist, data=dat))$r.squared
T2 = 1 - R2
T2
VIF2 = 1 / T2
VIF2

R3 <- summary(lm(wrist ~ tight + triceps, data=dat))$r.squared
T3 = 1 - R3
T3
VIF3 = 1 / T3
VIF3
```

# Calculating X'X matrix
```{r}
X <- as.matrix(dat[2:4])
XX <- t(X) %*% X

eigenvalue <- eigen(XX)$values
eigenvalue

sqrt(max(eigenvalue)/eigenvalue)
```

# Analysis All Variables
```{r}
result1 <- lm (fat ~ . , data=dat)
summary(result1)

result2 <- lm (fat ~ triceps + wrist, data=dat)
summary(result2)

result3 <- lm (fat ~ tight + wrist, data=dat)
summary(result3)
```

# Leverage, Cook's Distance
```{r}
result <- lm(fat ~., data=dat)
residual <- residuals(result)
stresidual <- rstudent(result)
stresidual[(abs(stresidual))>2]

res.inf <- influence(result)
round (res.inf$hat, 3)

cook <- cooks.distance (result)
round (cook, 3)
```

# Partial Residual Plot
```{r}
library(faraway)
par(mfrow=c(1,3))
prplot(result, 1)
prplot(result, 2)
prplot(result, 3)
```

# Selection of Variables
## 1. Forward Selection
```{r}
stress <- read.table("stress.txt", header=T, sep="\t")
res <- lm(Y ~ 1, data=stress)
summary(res)

res1 <- update (res, .~. + X1, data=stress)
anova(res, res1)

res2 <- update (res, .~. + X2, data=stress)
anova(res, res2)

res3 <- update (res, .~. + X1 + X3, data=stress)
anova(res, res3)

res4 <- update (res, .~. + X1 + X3 + X4, data=stress)
anova(res, res4)
```

## 2. Backward Elimination
```{r}
res <- lm(Y ~ X1 + X2 + X3 + X4, data=stress)
summary(res)

res2 <- update(res, .~. - X2)
anova(res, res2)

res3 <- lm(Y ~ X1 + X3 + X4, data=stress)
summary(res3)
```

## 3. Step-wise regression
```{r}
step(res)
```


