# Q1.
string = 'Central Nervous System Neoplasms'
string[ :15]
string[ 8:22]
string[ 16: ]

# Q2. 
string = string.upper()
print string

# Q3.
str_split = string.split()
print str_split

# Q4.
print "-".join( str_split )

# Q5.
sequence = '''CTGCTGTGCAGGGCAGGGAAGCTCCAGGCAAACAGCCCAGCAAACAGCAGCACTCAGCTAAAAGGAAGAC
TCACAGAACACAGTTGAAGAAGGAAAGTGGCGATGGACCTCATCCCAAATTTGGCGGTGGAAACCTGGCT
TCTCCTGGCTGTCAGCCTGGTGCTCCTCTATCTATATGGGACCCGTACACATGGACTTTTTAAGAGACTG
GGAATTCCAGGGCCCACACCTCTGCCTTTGTTGGGAAATGTTTTGTCCTATCGTCAGGGTCTCTGGAAAT
TTGACACAGAGTGCTATAAAAAGTATGGAAAAATGTGGGGAACGTATGAAGGTCAACTCCCTGTGCTGGC
CATCACAGATCCCGACGTGATCAGAACAGTGCTAGTGAAAGAATGTTATTCTGTCTTCACAAATCGAAGG
TCTTTAGGCCCAGTGGGATTTATGAAAAGTGCCATCTCTTTAGCTGAGGATGAAGAATGGAAGAGAATAC
GGTCATTGCTGTCTCCAACCTTCACCAGCGGAAAACTCAAGGAGATGTTCCCCATCATTGCCCAGTATGG
AGATGTATTGGTGAGAAACTTGAGGCGGGAAGCAGAGAAAGGCAAGCCTGTCACCTTGAAAGACATCTTT
GGGGCCTACAGCATGGATGTGATTACTGGCACATCATTTGGAGTGAACATCGACTCTCTCAACAATCCAC
AAGACCCCTTTGTGGAGAGCACTAAGAAGTTCCTAAAATTTGGTTTCTTAGATCCATTATTTCTCTCAAT
AATACTCTTTCCATTCCTTACCCCAGTTTTTGAAGCATTAAATGTCTCTCTGTTTCCAAAAGATACCATA
AATTTTTTAAGTAAATCTGTAAACAGAATGAAGAAAAGTCGCCTCAACGACAAACAAAAGCACCGACTAG
ATTTCCTTCAGCTGATGATTGACTCCCAGAATTCGAAAGAAACTGAGTCCCACAAAGCTCTGTCTGATCT
GGAGCTCGCAGCCCAGTCAATAATCTTCATTTTTGCTGGCTATGAAACCACCAGCAGTGTTCTTTCCTTC
ACTTTATATGAACTGGCCACTCACCCTGATGTCCAGCAGAAACTGCAAAAGGAGATTGATGCAGTTTTGC
CCAATAAGGCACCACCTACCTATGATGCCGTGGTACAGATGGAGTACCTTGACATGGTGGTGAATGAAAC
ACTCAGATTATTCCCAGTTGCTATTAGACTTGAGAGGACTTGCAAGAAAGATGTTGAAATCAATGGGGTA
TTCATTCCCAAAGGGTCAATGGTGGTGATTCCAACTTATGCTCTTCACCATGACCCAAAGTACTGGACAG
AGCCTGAGGAGTTCCGCCCTGAAAGGTTCAGTAAGAAGAAGGACAGCATAGATCCTTACATATACACACC
CTTTGGAACTGGACCCAGAAACTGCATTGGCATGAGGTTTGCTCTCATGAACATGAAACTTGCTCTAATC
AGAGTCCTTCAGAACTTCTCCTTCAAACCTTGTAAAGAAACACAGATCCCCTTGAAATTAGACACGCAAG
GACTTCTTCAACCAGAAAAACCCATTGTTCTAAAGGTGGATTCAAGAGATGGAACCCTAAGTGGAGAATG
AGTTATTCTAAGGATTTCTACTTTGGTCTTCAAGAAAGCTGTGCCCCAGA  ACACCAGAGATTTCAACTTA
GTCAATAAAACCTTGAAATAAAGATGGGCTTAATCTAATGTACTGC     '''

sequence = sequence.upper()
sequence = sequence.replace('\n', '')
sequence = sequence.replace(" ", "")
sequence

G = sequence.count('G')
C = sequence.count('C')

GC = (float)(G + C)/len(sequence) * 100

print "Sequence length = %d , No.of G = %d , No. of C = %d , GC contents = %.2f%%" % ( len(sequence), G, C, GC )
